#!/usr/bin/env python

import sys

from SimpleSPARQL import Axpress        
axpress = Axpress(options = [])

ret = axpress.read_translate("""
    x[axpress.is] = "%s"
    x[speech.out] = _out
""" % ' '.join(sys.argv[1:]))

# just print the first answer for now
if ret and 'out' in ret[0] :
   for r in ret :
       print r['out']
