#!/usr/bin/env python

import sys

from SimpleSPARQL import Axpress, loadTranslations
        
axpress = Axpress()
loadTranslations(axpress)

cmd = ' '.join(sys.argv[1:])

print cmd
ret = axpress.read_translate("""
    x[axpress.is] = "%s"
    x[speech.out] = _out
""" % cmd)

if ret and 'out' in ret[0] :
   for r in ret :
       print r['out']