/* CVS $Id: JosekiSchemaBase.java,v 1.2 2008/12/30 19:48:35 andy_seaborne Exp $ */
package org.joseki.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from joseki-schema.ttl 
 * @author Auto-generated by schemagen on 03 Oct 2006 13:57 
 */
public class JosekiSchemaBase {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://joseki.org/2005/06/configuration#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>query operation name</p> */
    public static final Property queryOperationName = m_model.createProperty( "http://joseki.org/2005/06/configuration#queryOperationName" );
    
    public static final Property allowExplicitDataset = m_model.createProperty( "http://joseki.org/2005/06/configuration#allowExplicitDataset" );
    
    public static final Property allowWebLoading = m_model.createProperty( "http://joseki.org/2005/06/configuration#allowWebLoading" );
    
    public static final Property lockingPolicy = m_model.createProperty( "http://joseki.org/2005/06/configuration#lockingPolicy" );
    
    /** <p>Other resources to read and merge (e.g. file:...)</p> */
    public static final Property include = m_model.createProperty( "http://joseki.org/2005/06/configuration#include" );
    
    public static final Property dataset = m_model.createProperty( "http://joseki.org/2005/06/configuration#dataset" );

    public static final Property poolSize = m_model.createProperty( "http://joseki.org/2005/06/configuration#poolSize" );
    
    /** <p></p> */
    public static final Property defaultGraph = m_model.createProperty( "http://joseki.org/2005/06/configuration#defaultGraph" );
    
    /** <p></p> */
    public static final Property graphData = m_model.createProperty( "http://joseki.org/2005/06/configuration#graphData" );
    
    /** <p>URI reference for service URI (relative to where the server is)</p> */
    public static final Property processor = m_model.createProperty( "http://joseki.org/2005/06/configuration#processor" );
    
    public static final Property initialization = m_model.createProperty( "http://joseki.org/2005/06/configuration#initialization" );
    
    /** <p>URI reference for service URI (relative to where the server is)</p> */
    public static final Property serviceRef = m_model.createProperty( "http://joseki.org/2005/06/configuration#serviceRef" );
    
    /** <p></p> */
    public static final Property namedGraph = m_model.createProperty( "http://joseki.org/2005/06/configuration#namedGraph" );
    
    /** <p></p> */
    public static final Property graphName = m_model.createProperty( "http://joseki.org/2005/06/configuration#graphName" );
    
    /** <p>Processor</p> */
    public static final Resource Processor = m_model.createResource( "http://joseki.org/2005/06/configuration#Processor" );
    
    /** <p></p> */
    public static final Resource RDFDataSet = m_model.createResource( "http://joseki.org/2005/06/configuration#RDFDataSet" );
    
    /** <p>Server</p> */
    public static final Resource Server = m_model.createResource( "http://joseki.org/2005/06/configuration#Server" );
    
}
