/* CVS $Id: TestProtocolVocab.java,v 1.3 2006/01/06 18:05:35 andy_seaborne Exp $ */
package org.joseki.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from test-protocol.ttl 
 * @author Auto-generated by schemagen on 06 Jan 2006 17:39 
 */
public class TestProtocolVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property graphData = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#graphData" );
    
    public static final Property graphName = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#graphName" );
    
    public static final Property resultCode = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#resultCode" );
    
    public static final Property serviceDataSet = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#serviceDataSet" );
    
    public static final Property entries = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#entries" );
    
    public static final Property defaultGraph = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#defaultGraph" );
    
    public static final Property resultContentType = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#resultContentType" );
    
    public static final Property queryDataSet = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#queryDataSet" );
    
    public static final Property dataSet = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#dataSet" );
    
    public static final Property result = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#result" );
    
    public static final Property comment = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#comment" );
    
    public static final Property namedGraph = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#namedGraph" );
    
    public static final Property service = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#service" );
    
    public static final Property name = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#name" );
    
    public static final Property preferredResult = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#preferredResult" );
    
    public static final Property acceptType = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#acceptType" );
    
    public static final Property query = m_model.createProperty( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#query" );
    
    public static final Resource Manifest = m_model.createResource( "http://www.w3.org/2001/sw/DataAccess/proto-tests/test-manifest#Manifest" );
    
}
